# Generated by Django 5.2 on 2026-04-08 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_category_options_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="min_group",
            field=models.IntegerField(
                choices=[(10, "große Gruppe"), (5, "kleine Gruppe")], default=5
            ),
        ),
    ]
